spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://127.0.0.1:5432/test_data?currentSchema=task
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create
server:
  port: 9003
  servlet:
    context-path: /task
zk:
  address: 127.0.0.1:2181
